# Generated by Django 5.0.2 on 2024-09-18 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_remove_task_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='admin_id',
            new_name='admin',
        ),
    ]
