# Generated by Django 5.0.2 on 2024-09-18 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='sender_id',
            new_name='sender',
        ),
    ]
